### ISSUE TITLE
crashes with message payload must be....

### ISSUE THREAD

**Issue by 885narrow** [mverleun/RTL433-to-mqtt#14]
Hi, it runns nice but crashes shortly after starting sometimes.
the line number is much to high.
is this because the 433 delivered a broken data signal?
thank you!!

Tuned to 433.920MHz.

Traceback (most recent call last):
  File "/home/pi/./rtl2mqtt.py", line 102, in <module>
    mqttc.publish(MQTT_TOPIC+"/"+subtopic+"/"+item, payload=value, qos=MQTT_QOS, retain=True)
  File "/home/pi/.local/lib/python3.9/site-packages/paho/mqtt/client.py", line 1247, in publish
    raise TypeError(
TypeError: payload must be a string, bytearray, int, float or None.

**Comment by Jodaille** [comment]
Hello,
I have added a try/except, maybe not the best way but it works :)
`                        try:
                            mqttc.publish(MQTT_TOPIC+"/"+subtopic+"/"+item, payload=value, qos=MQTT_QOS, retain=True)
                        except TypeError:
                            print("TypeError intercepted")
`
https://gist.github.com/Jodaille/38a12c2b8851b8b35a22a55442e47f13#file-rtlsendmqtt-py-L128-L131

I have sometimes crazy values for temperature, I have tried to not publish this values (l-124).
And I have tried to not publish values if temperature does not change.

Thank you @mverleun  ! Your script helps me a lot :)
