### ISSUE TITLE
errors when I try to run rt2qtt.py

### ISSUE THREAD

**Issue by grilli303** [mverleun/RTL433-to-mqtt#4]
Hi,

I tried to get the Python script working and try o set it up like the desription.
the rtl_433 module is installed and run as it should.
When I try to run the" rt2qtt.py" script with the program called "thony python IDE", 
but I get the following errors:

maybe it could have to do with the path of the files.
I saved the in the folowing directory: /home/pi/RTL433-to-mqtt

Traceback (most recent call last):
  File "/home/pi/RTL433-to-mqtt/src/rtl2mqtt.py", line 51, in <module>
    mqttc.connect(MQTT_HOST, MQTT_PORT, 60)
  File "/usr/local/lib/python3.7/dist-packages/paho/mqtt/client.py", line 839, in connect
    return self.reconnect()
  File "/usr/local/lib/python3.7/dist-packages/paho/mqtt/client.py", line 962, in reconnect
    sock = socket.create_connection((self._host, self._port), source_address=(self._bind_address, 0))
  File "/usr/lib/python3.7/socket.py", line 727, in create_connection
    raise err
  File "/usr/lib/python3.7/socket.py", line 716, in create_connection
    sock.connect(sa)
OSError: [Errno 113] No route to host

PS, I'm just starting to use Python, so i'm a "newbie" in that.
thank you for helping me.

**Comment by gazzat5** [comment]
Sounds like your problem is your machine cannot connect to your broker.
